gds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('optimus/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('', RedirectView.as_view(url='/auth/login/', permanent=False), name='landing'),
    path('auth/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('stock/', include('stock.urls')),
    path('transactions/', include('transactions.urls')),
    path('requisitions/', include('requisition.urls')),
    path('billing/', include('billing.urls')),
]

billing/models.py
from random import choices
from django.db import models
import uuid
from django.urls import reverse
from payments import PurchasedItem
from payments.models import BasePayment


STATUS_CHOICES = (('Active', 'Active'), ('Suspended', 'Suspended'))

class SubscriptionPlan(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price_per_site = models.DecimalField(max_digits=10, decimal_places=2)
    max_sites = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"

class BillingProfile(models.Model):
    class Meta:
            indexes = [
            models.Index(fields=['company']),
            models.Index(fields=['subscription_status']),
        ]
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    admin = models.OneToOneField('accounts.User', null=True, blank=True, on_delete=models.SET_NULL, )
    company = models.ForeignKey('accounts.Company', on_delete=models.CASCADE, related_name='bill_profiles')
    subscription_plan = models.ForeignKey(SubscriptionPlan, on_delete=models.SET_NULL, null=True, blank=True)
    subscription_status = models.CharField(max_length=50, default='Active', choices=STATUS_CHOICES)
    last_payment_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def calculate_total_due(self):
        total_sites = self. company.sites.count()
        total_due = total_sites * self.subscription_plan.price_per_site
        return total_due

    def __str__(self):
        return f"{self.company.name} "

class Invoice(models.Model):
    CURRENCY_CHOICES = [
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
        ('GBP', 'British Pound'),
        ('ZWL', 'Zimbabwean Dollar'),       # Zimbabwe
        ('ZAR', 'South African Rand'),      # South Africa
        ('BWP', 'Botswana Pula'),           # Botswana
        ('NAD', 'Namibian Dollar'),         # Namibia
        ('MWK', 'Malawian Kwacha'),         # Malawi
        ('ZMW', 'Zambian Kwacha'),          # Zambia
        ('MZN', 'Mozambican Metical'),      # Mozambique
        ('SZL', 'Swazi Lilangeni'),         # Eswatini (Swaziland)
        ('LSL', 'Lesotho Loti'),            # Lesotho
        
    ]
    STATUS_CHOICES = [('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')]
    
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    billing_profile = models.ForeignKey('BillingProfile', on_delete=models.CASCADE)
    site = models.ForeignKey('accounts.Site', on_delete=models.CASCADE, null=True, blank=True, related_name='invoices')
    date_issued = models.DateField(auto_now_add=True)
    amount_due = models.DecimalField(max_digits=10, decimal_places=2)
    due_date = models.DateField()
    currency = models.CharField(max_length=255, choices=CURRENCY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    payment_date = models.DateField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_amount(self):
        return self.amount_due

    def get_currency(self):
        return self.currency

    def save(self, *args, **kwargs):
        if not self.amount_due:
            self.amount_due = self.billing_profile.calculate_total_due()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Invoice {self.pk} for {self.billing_profile.company.name}"


class Payment(BasePayment):
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    PAYMENT_CHOICES = [('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')]
    invoice = models.ForeignKey(Invoice, related_name='payments', on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=50, choices=PAYMENT_CHOICES)
    poll_url = models.URLField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_failure_url(self):
        return reverse('payment_failed')

    def get_success_url(self):
        return reverse('payment_success')

    def get_purchased_items(self):
        yield PurchasedItem(
            name=f"Invoice {self.invoice.uuid}",
            quantity=self.invoice.billing_profile.company.site_count(),
            price=self.invoice.get_amount(),
            currency=self.invoice.get_currency(),
            sku=f"invoice-{self.invoice.uuid}"
        )

stock/models.py
from django.db import models


class Stock(models.Model):
    name = models.CharField(max_length=100)
    site = models.ForeignKey('accounts.Site', on_delete=models.SET_NULL, null=True, blank=True, related_name='stock')
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    supplier = models.CharField(max_length=100, null=True, blank=True)
    minimum_threshold = models.PositiveIntegerField(default= 50)
    unit = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['site']),
            models.Index(fields=['quantity']),
            models.Index(fields=['price']),
            models.Index(fields=['supplier']),
            models.Index(fields=['created']),
        ]


    def __str__(self):
        return f"{self.name}"
    
class Reciept(models.Model):
    site = models.ForeignKey('accounts.Site', on_delete=models.SET_NULL, null=True, blank=True, related_name='requisitions')
    quantity = models.PositiveIntegerField()
    stock = models.ForeignKey(Stock, related_name='reciepts', on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['site']),
            models.Index(fields=['stock']),
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f"{self.stock} - {self.quantity}"

templates/sites/detail.html
{% extends 'layouts/base.html' %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% load static %}

{% block body %}
<div class="nk-content my-5">
<div class="row g-gs">
    <div class="col-lg-6">
        <div class="card h-100">
            <div class="card-inner">
                <div class="card-head">
                    <h5 class="card-title">Site: {{ site }}</h5>
                </div>
                <ul class="nk-store-statistics">
                    <li class="item">
                        <div class="info">
                            <div class="title">Company</div>
                            <div class="count">{{ site.company }}</div>
                        </div>
                        <em class="icon bg-primary-dim ni ni-template"></em>
                    </li>
                    <li class="item">
                        <div class="info">
                            <div class="title">Capacity</div>
                            <div class="count">{{ site.capacity }}kg</div>
                        </div>
                        <em class="icon bg-primary-dim ni ni-db"></em>
                    </li>
                    <li class="item">
                        <div class="info">
                            <div class="title">Contact</div>
                            <div class="count">{{ site.contact  }}</div>
                        </div>
                        <em class="icon bg-purple-dim ni ni-mobile"></em>
                    </li>
                    <li class="item">
                        <div class="info">
                            <div class="title">Adress</div>
                            <div class="count">{{ site.address  }}</div>
                        </div>
                        <em class="icon bg-purple-dim ni ni-map"></em>
                    </li>
                    <li class="item">
                        <div class="info">
                            <div class="title">Operator</div>
                            <div class="count">{{ site.operator }}</div>
                        </div>
                        <em class="icon bg-purple-dim ni ni-user-c"></em>
                    </li>
                    <li class="item">
                        <div class="info">
                            <div class="title">Manager</div>
                            <div class="count">{{ site.manager }}</div>
                        </div>
                        <em class="icon bg-purple-dim ni ni-user-c"></em>
                    </li>
                    
                    
                    <li class="item">
                        <div class="info">
                            <div class="title">Created On</div>
                            <div class="count">{{ site.created }}</div>
                        </div>
                        <em class="icon bg-purple-dim ni ni-clock"></em>
                    </li>
                     
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="row g-gs">
        <div class="col-xxl-12 ">
            <div class="card">
                <div class="nk-ecwg nk-ecwg3">
                    <div class="card-inner pb-0">
                        <div class="card-title-group">
                            <div class="card-title">
                                <h6 class="title">Remaining Stock</h6>
                            </div>
                        </div>
                        <div class="data">
                            <div class="data-group">
                                <div class="amount">{{site.stock.first.quantity}} kg</div>
                                </div>
                        </div>
                    </div><!-- .card-inner -->
                    <div class="nk-ecwg3-ck"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                        <canvas class="ecommerce-line-chart-s1 chartjs-render-monitor" id="totalCustomers" width="988" height="132" style="display: block; height: 66px; width: 494px;"></canvas>
                    </div>
                </div><!-- .nk-ecwg -->
            </div><!-- .card -->
        </div>
    </div>
    <div class="row g-gs my-1">
        <div class="col-xxl-12 ">
            <div class="card">
                <div class="nk-ecwg nk-ecwg3">
                    <div class="card-inner pb-0">
                        <div class="card-title-group">
                            <div class="card-title">
                                <h6 class="title">Selling Price </h6>
                            </div>
                        </div>
                        <div class="data">
                            <div class="data-group">
                                <div class="amount">${{ site.stock.first.price|format_amount }} </div>
                                </div>
                        </div>
                    </div><!-- .card-inner -->
                    <div class="nk-ecwg3-ck"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                        <canvas class="ecommerce-line-chart-s1 chartjs-render-monitor" id="totalOrders" width="988" height="132" style="display: block; height: 66px; width: 494px;"></canvas>
                    </div>
                </div><!-- .nk-ecwg -->
            </div><!-- .card -->
        </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

templates/sites/index.html
{% extends 'layouts/base.html' %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% load static %}

{% block body %}
<div class="nk-content my-5">
    {% if add_site_form.errors %}
    {% for error in add_site_form.errors %}
      <div class="alert alert-pro alert-danger">
        {{ error }}: {{error.message}}
      </div>
    {% endfor %}
  {% endif %}
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block-head nk-block-head-sm">
                    <div class="nk-block-between">
                       
                        <div class="nk-block-head-content">
                            <div class="toggle-wrap nk-block-tools-toggle">
                                <a class="btn btn-icon btn-trigger toggle-expand me-n1"  data-target="pageMenu"><em  class="icon ni ni-more-v"></em></a>
                                <div class="toggle-expand-content" data-content="pageMenu">
                                    <ul class="nk-block-tools g-3">
                                        <li class="nk-block-tools-opt">
                                            <a href="#" data-bs-toggle="modal"  data-bs-target="#addSiteModal" class="btn btn-icon btn-primary d-md-none"><em class="icon ni ni-plus"></em></a>
                                            <a href="#" data-bs-toggle="modal" data-bs-target="#addSiteModal" class="btn btn-primary d-none d-md-inline-flex"><em class="icon ni ni-plus"></em><span>Add Site</span></a>
                                        </li>
                                        <li>
                                            <div class="drodown">
                                                <a href="#" class="dropdown-toggle dropdown-indicator btn btn-outline-light btn-white" data-bs-toggle="dropdown">Status</a>
                                                <div class="dropdown-menu dropdown-menu-end">
                                                    <ul class="link-list-opt no-bdr">
                                                        <li><a href="{% url 'site_filter' %}?status=Active"><span>Active</span></a></li>
                                                        <li><a href="{% url 'site_filter' %}?status=Suspended"><span>Suspended</span></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .nk-block-head-content -->
                    </div><!-- .nk-block-between -->
                </div><!-- .nk-block-head -->
                <div class="nk-block">
                    <div class="nk-tb-list is-separate is-medium mb-3">
                        <div class="nk-tb-item nk-tb-head">
                           
                            <div class="nk-tb-col tb-col-md"><span>Title</span></div>
                            <div class="nk-tb-col"><span class="d-none d-sm-block">Status</span></div>
                            <div class="nk-tb-col tb-col-sm"><span>Contact</span></div>
                            <div class="nk-tb-col tb-col-md"><span>Capacity</span></div>
                            <div class="nk-tb-col nk-tb-col-tools">
                            </div>
                        </div><!-- .nk-tb-item -->
                        <!-- .nk-tb-item -->
                         {% for site in sites %}
                        <div class="nk-tb-item">
                            
                            <div class="nk-tb-col">
                                <span class="tb-lead"><a href="{% url 'site_detail' site.uuid %}">{{ site }}</a></span>
                            </div>

                            <div class="nk-tb-col">
                                <span class="dot bg-success d-sm-none"></span>
                                <span class="badge badge-sm badge-dot has-bg bg-{% if site.status == 'Active' %}success{% else %}warning{% endif %} d-none d-sm-inline-flex">{{ site.status }}</span>
                            </div>
                            <div class="nk-tb-col tb-col-sm">
                                <span class="tb-sub">{{ site.contact }}</span>
                            </div>
                            <div class="nk-tb-col tb-col-md">
                                <span class="tb-sub text-primary">{{ site.capacity }}kg</span>
                            </div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1">
                                    
                                  <li>
                                        <div class="drodown me-n1">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-bs-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-end">
                                                <ul class="link-list-opt no-bdr">
                                                    <li><a href="{% url 'site_detail' site.uuid %}"><em class="icon ni ni-eye"></em><span>View Site</span></a></li>
                                                    <li><a href="{% url 'site_update' site.uuid %}"><em class="icon ni ni-pen"></em><span>Update Site</span></a></li>
                                                    <li data-bs-toggle="modal" data-bs-target="#addStaffModal{{ site.pk }}"><a ><em class="icon ni ni-user-check"></em><span>Add Staff</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-tb-item -->
                            <!-- Modal Alert -->
    <div class="modal fade" tabindex="-1" id="addStaffModal{{ site.pk }}">
       
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Add New Staff</h5>
                        <a href="#" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <em class="icon ni ni-cross"></em>
                        </a>
                    </div>``
                    <div class="modal-body">
                        <form action="{% url 'create_staff_user' site.pk %}" method="POST">
                            {% csrf_token %}
                            <div class="row g-4">
                                {{ add_staff_form.as_p }}
                               
                                <div class="col-12">
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-lg btn-primary" value="save">Save</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer bg-light">
                        <span class="sub-text">Endframe</span>
                    </div>
                </div>
            </div>
    
    </div>
    <div class="modal fade" tabindex="-1" id="removeSaleModal{{ sale.pk }}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <a href="#" class="close" data-bs-dismiss="modal"><em class="icon ni ni-cross"></em></a>
                <div class="modal-body modal-body-lg text-center">
                    <div class="nk-modal">
                        <em class="nk-modal-icon icon icon-circle icon-circle-xxl ni ni-cross bg-danger"></em>
                        <h4 class="nk-modal-title">Remove!</h4>
                        <div class="nk-modal-text">
                            <div class="caption-text">Are you sure you want to delete this sale <strong>{{ sale.order_number }}</strong></div>
                           </div>
                        <div class="nk-modal-action">
                            <a href="#" class="btn btn-lg btn-mw btn-light" data-bs-dismiss="modal">Cancel</a>
                            <a href="{% url 'transaction_delete' site.pk %}" class="btn btn-lg btn-mw btn-dark" >Remove</a>
                        </div>
                    </div>
                </div><!-- .modal-body -->
                <div class="modal-footer bg-lighter">
                    
                </div>
            </div>
        </div>
    </div>
    
                        {% endfor %}
                              </div><!-- .nk-tb-list -->
                    
                </div><!-- .nk-block -->
            </div>
        </div>
    </div>
</div>

<!-- Add Site modal -->
<div class="modal fade" id="addSiteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add New Site</h5>
                <a href="#" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <em class="icon ni ni-cross"></em>
                </a>
            </div>
            <div class="modal-body">
                <form action="{% url 'create_site' %}" method="POST">
                    {% csrf_token %}
                    <div class="row g-4">
                        {{ add_site_form.as_p }}
                        <input type="hidden" name="company" value={{ request.user.company}} id="id_company">
                        <div class="col-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-primary" value="save">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer bg-light">
                <span class="sub-text">Endframe</span>
            </div>
        </div>
    </div>
</div>
<!-- ./Add Sale modal -->
{% endblock %}

templates/sites/update.html
{% extends 'layouts/base.html' %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% load static %}

{% block body %}
    <div class="nk-content my-5">
        {% if form.errors %}
        {% for error in form.errors %}
        <div class="alert alert-pro alert-danger">
            {{ error }}: {{error.message}}
        </div>
        {% endfor %}
    {% endif %}
    
    <div class="nk-block">
        <div class="card h-100 m-2 p-2">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- Render form fields as paragraphs -->
            <p>
            <label for="id_price">Price:</label>
            <input type="hidden" name="company" value={{ request.user.company}} id="id_company">
            <input type="number" name="price" class="form-control" value = "{{form.instance.stock.first.price}}" required step="0.01" id="id_price">
            </p>
            <button class="btn btn-lg btn-primary btn-block my-1" type="submit">Save</button>
          </form>
        </div>
    </div>
    </div>
  {% endblock %}