gds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('optimus/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('', RedirectView.as_view(url='/auth/login/', permanent=False), name='landing'),
    path('auth/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('stock/', include('stock.urls')),
    path('transactions/', include('transactions.urls')),
    path('requisitions/', include('requisition.urls')),
    path('billing/', include('billing.urls')),
]

billing/models.py
from random import choices
from django.db import models
import uuid
from django.urls import reverse
from payments import PurchasedItem
from payments.models import BasePayment


STATUS_CHOICES = (('Active', 'Active'), ('Suspended', 'Suspended'))

class SubscriptionPlan(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price_per_site = models.DecimalField(max_digits=10, decimal_places=2)
    max_sites = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"

class BillingProfile(models.Model):
    class Meta:
            indexes = [
            models.Index(fields=['company']),
            models.Index(fields=['subscription_status']),
        ]
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    admin = models.OneToOneField('accounts.User', null=True, blank=True, on_delete=models.SET_NULL, )
    company = models.ForeignKey('accounts.Company', on_delete=models.CASCADE, related_name='bill_profiles')
    subscription_plan = models.ForeignKey(SubscriptionPlan, on_delete=models.SET_NULL, null=True, blank=True)
    subscription_status = models.CharField(max_length=50, default='Active', choices=STATUS_CHOICES)
    last_payment_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def calculate_total_due(self):
        total_sites = self. company.sites.count()
        total_due = total_sites * self.subscription_plan.price_per_site
        return total_due

    def __str__(self):
        return f"{self.company.name} "

class Invoice(models.Model):
    CURRENCY_CHOICES = [
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
        ('GBP', 'British Pound'),
        ('ZWL', 'Zimbabwean Dollar'),       # Zimbabwe
        ('ZAR', 'South African Rand'),      # South Africa
        ('BWP', 'Botswana Pula'),           # Botswana
        ('NAD', 'Namibian Dollar'),         # Namibia
        ('MWK', 'Malawian Kwacha'),         # Malawi
        ('ZMW', 'Zambian Kwacha'),          # Zambia
        ('MZN', 'Mozambican Metical'),      # Mozambique
        ('SZL', 'Swazi Lilangeni'),         # Eswatini (Swaziland)
        ('LSL', 'Lesotho Loti'),            # Lesotho
        
    ]
    STATUS_CHOICES = [('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')]
    
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    billing_profile = models.ForeignKey('BillingProfile', on_delete=models.CASCADE)
    site = models.ForeignKey('accounts.Site', on_delete=models.CASCADE, null=True, blank=True, related_name='invoices')
    date_issued = models.DateField(auto_now_add=True)
    amount_due = models.DecimalField(max_digits=10, decimal_places=2)
    due_date = models.DateField()
    currency = models.CharField(max_length=255, choices=CURRENCY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    payment_date = models.DateField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_amount(self):
        return self.amount_due

    def get_currency(self):
        return self.currency

    def save(self, *args, **kwargs):
        if not self.amount_due:
            self.amount_due = self.billing_profile.calculate_total_due()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Invoice {self.pk} for {self.billing_profile.company.name}"


class Payment(BasePayment):
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    PAYMENT_CHOICES = [('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')]
    invoice = models.ForeignKey(Invoice, related_name='payments', on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=50, choices=PAYMENT_CHOICES)
    poll_url = models.URLField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_failure_url(self):
        return reverse('payment_failed')

    def get_success_url(self):
        return reverse('payment_success')

    def get_purchased_items(self):
        yield PurchasedItem(
            name=f"Invoice {self.invoice.uuid}",
            quantity=self.invoice.billing_profile.company.site_count(),
            price=self.invoice.get_amount(),
            currency=self.invoice.get_currency(),
            sku=f"invoice-{self.invoice.uuid}"
        )

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <base href="../">
    <meta charset="utf-8">
    <meta name="author" content="Nyasha Chizampeni">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A sales application">

    <meta name="theme-color" content="white">
``
    <!-- manifest.json  -->
    <link rel="manifest" href='{% static "manifest.json" %}'>
    <!-- IE11 & Safari Support  -->
    <link rel="apple-touch-icon" href='{% static "static/images/favicon.png" %}'>
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href='{% static "images/favicon.png" %}'>

    <script>
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register("{% static 'service-worker.js' %}")
            .then((registration) => {
                console.log('Service Worker registered with scope:', registration.scope);
            })
            .catch((error) => {
                console.error('Service Worker registration failed:', error);
            });
        }
    </script>
    <!-- Page Title  -->
    <title>GDS</title>
    <!-- StyleSheets  -->
    {% include "layouts/styles.html" %}
</head>

<body class="nk-body bg-lighter npc-general has-sidebar ">
    <div class="nk-app-root">
        <!-- main @s -->
        <div class="nk-main ">
            <!-- sidebar @s -->
            {% include "layouts/sidebar.html" %}
            <!-- sidebar @e -->
            <!-- wrap @s -->
            <div class="nk-wrap">
                <!-- main header @s -->
                {% include "layouts/header.html" %}
                <!-- main header @e -->
                {% include "layouts/messages.html" %}
                <!-- content @s -->
                <div class="py-2 my-2">
                {% block body %}
                {% endblock %}
                </div>
                <!-- content @e -->
                <!-- footer @s -->
                {% include "layouts/footer.html" %}
                <!-- footer @e -->
            </div>
            <!-- wrap @e -->
        </div>
        <!-- main @e -->
    </div>
    <!-- app-root @e -->
    <!-- select region modal -->
    {% include "layouts/modals.html" %}
    <!-- JavaScript -->
     {% include "layouts/scripts.html" %}
    
</body>

</html>

templates/layouts/footer.html
{% load static %}

<div class="nk-footer">
  <div class="container-fluid">
      <div class="nk-footer-wrap">
          <div class="nk-footer-copyright"> &copy; EndFrame 2024 
          </div>
          
      </div>
  </div>
</div>

templates/layouts/header.html
{% load static %}
<div class="nk-header is-light nk-header-fixed has-fixed">
    <div class="container-xl wide-xl">
        <div class="nk-header-wrap">
            <div class="nk-menu-trigger d-xl-none ms-n1 me-3">
                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
            </div>
            <!-- .nk-header-brand -->
            <div class="nk-header-menu is-light mobile-menu">
                
            </div><!-- .nk-header-menu -->
            <div class="nk-header-tools">
                <ul class="nk-quick-nav">
                    
                    
                    <!-- .dropdown -->
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                            <div class="user-toggle">
                                <div class="user-avatar sm">
                                    <em class="icon ni ni-user-alt"></em>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-end">
                            <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                                <div class="user-card">
                                    <div class="user-avatar">
                                        <span>{{ request.user.avatar }}</span>
                                    </div>
                                    <div class="user-info">
                                        <span class="lead-text">{{ request.user }}</span>
                                        <span class="sub-text">{{ request.user.role }}</span>
                                        <span class="sub-text">{{ request.user.operation_site }}{{ request.user.managed_site }}</span>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="dropdown-inner">
                               
                            </div>
                            <div class="dropdown-inner">
                                <ul class="link-list">
                                    <li><a class="text-danger" href="{% url 'account_logout' %}"><em class="icon ni ni-signout"></em><span >Sign out</span></a></li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div><!-- .nk-header-tools -->
        </div><!-- .nk-header-wrap -->
    </div><!-- .container-fliud -->
</div>

templates/layouts/messages.html
{% if messages %}

<ul class="messages my-5 py-4 mx-2 px-2" >
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-pro alert-{{ message.tags }} " {% endif %} role="alert">
        {{ message }}
      </div>
   
    {% endfor %}
</ul>
{% endif %}

templates/layouts/modals.html
{% load static %}
<!-- select region modal -->
<div class="modal fade" id="getReportModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Generate Report</h5>
          <a href="#" class="close" data-bs-dismiss="modal" aria-label="Close">
            <em class="icon ni ni-cross"></em>
          </a>
        </div>
        <div class="modal-body">
  
            <div class="row g-4">
              <form action="{% url 'report_create' %}" method="post">
                  {% csrf_token %}
                <div class="row g-4">
                  
  
                  <div>
                    <label for="id_customer">Month:</label>
  
                    <input
                      type="month"
                      name="month"
                      class="form-control"
                      id="id_customer"
                    />
                  </div>
  
                  <div>
                    <label for="id_status">Report Type:</label>
  
                    <select name="report_type" class="form-control" id="id_status">
                      <option value="sales_report" >Sales Report</option>
                      <option value="requisition_report">Requisition Report</option>
                      <option value="inventory_report">Inventory Report</option>
                    </select>
  
                    
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <button
                        type="submit"
                        class="btn btn-lg btn-primary"
                        value="save"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                </div>
              </form>
            
        </div>
        
      </div>
    </div>
  </div>
  </div>
<!-- .modal -->

templates/layouts/scripts.html
{% load static %}
    <script src="{% static 'assets/js/bundle.js?ver=3.1.1' %}"></script>
    <script src="{% static 'assets/js/scripts.js?ver=3.1.1' %}"></script>
    <script src="{% static 'assets/js/charts/chart-ecommerce.js?ver=3.1.1' %}"></script>
    <script src="{% static 'assets/js/example-sweetalert.js?ver=3.1.1' %}"></script>

templates/layouts/sidebar.html
{% load static %}

<div class="nk-sidebar nk-sidebar-fixed is-light" data-content="sidebarMenu">
  <div class="nk-sidebar-element nk-sidebar-head">
      <div class="nk-sidebar-brand">
        <a href="{% url 'dashboard' %}" class="logo-link nk-sidebar-logo">
            <span class="nk-menu-text h4 nk-title">{{ request.user.company }}</span>
            <span class="sub-text">{{ request.user.operation_site }}{{ request.user.managed_site }}</span>
        </a>
      </div>
      <div class="nk-menu-trigger me-n2">
          <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
          <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
      </div>
  </div><!-- .nk-sidebar-element -->
  <div class="nk-sidebar-element">
      <div class="nk-sidebar-content">
          <div class="nk-sidebar-menu" data-simplebar>
              <ul class="nk-menu">
                  <li class="nk-menu-item">
                      <a href="{% url 'dashboard' %}" class="nk-menu-link">
                          <span class="nk-menu-icon"><em class="icon ni ni-dashboard-fill"></em></span>
                          <span class="nk-menu-text">Dashboard</span>
                      </a>
                  </li><!-- .nk-menu-item -->
                  <li class="nk-menu-item">
                      <a href="{% url 'transaction_list' %}" class="nk-menu-link">
                          <span class="nk-menu-icon"><em class="icon ni ni-bag-fill"></em></span>
                          <span class="nk-menu-text">Sales</span>
                      </a>
                  </li><!-- .nk-menu-item -->
                  <li class="nk-menu-item">
                      <a href="{% url 'requisition_list' %}" class="nk-menu-link">
                          <span class="nk-menu-icon"><em class="icon ni ni-truck"></em></span>
                          <span class="nk-menu-text">Requistions</span>
                      </a>
                  </li><!-- .nk-menu-item -->
                  <li class="nk-menu-item">
                    <a href="{% url 'reciept_list' %}" class="nk-menu-link">
                        <span class="nk-menu-icon"><em class="icon ni ni-truck"></em></span>
                        <span class="nk-menu-text">Stock</span>
                    </a>
                </li>
                {% if request.user.role == "Admin" or request.user.role == "SuperUser" %}
                  <!-- .nk-menu-item -->
                  <hr class="mx -auto bg-light">
                  <!-- .nk-menu-item -->
                 <!-- .nk-menu-item -->
                 <li class="nk-menu-item">
                  <a href="{% url 'site_list' %}" class="nk-menu-link">
                      <span class="nk-menu-icon"><em class="icon ni ni-location"></em></span>
                      <span class="nk-menu-text">Sites</span>
                  </a>
              </li><!-- .nk-menu-item -->
              <!-- .nk-menu-item -->
              <li class="nk-menu-item">
                  <a href="html/ecommerce/settings.html" class="nk-menu-link">
                      <span class="nk-menu-icon"><em class="icon ni ni-cc-alt"></em></span>
                      <span class="nk-menu-text">Payments</span>
                  </a>
              </li>
              {% endif %}
              </ul><!-- .nk-menu -->
          </div><!-- .nk-sidebar-menu -->
      </div><!-- .nk-sidebar-content -->
  </div><!-- .nk-sidebar-element -->
</div>

templates/layouts/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/dashlite.css?ver=3.1.1' %}">
<link id="skin-default" rel="stylesheet" href="{% static 'assets/css/theme.css?ver=3.1.1' %}">